### ISSUE TITLE
Not Revive

### ISSUE THREAD

**Issue by pil0lo** [BKPatt/lethalCompanyRevive#4]
revive player name
The player is not recognized.
Not revive
Why is that???

**Comment by BKPatt** [comment]
It is likely that either you are typing the name slightly wrong, not accounting for capitals, or there may be an issue with the name and parsing it. Are there numbers in their username? Could you try to type it without the numbers? If none of this works, I need more info to help

**Comment by pil0lo** [comment]
> 대문자를 고려하지 않고 이름을 약간 잘못 입력했거나 이름 및 구문 분석에 문제가 있을 수 있습니다. 사용자 이름에 숫자가 있나요? 숫자 없이 입력해 보시겠어요? 이 방법이 모두 작동하지 않으면 도움을 주기 위한 추가 정보가 필요합니다.

**Comment by pil0lo** [comment]
ah!
thank you
It was successful.

https://thunderstore.io/c/lethal-company/p/Deja/Revive/
It would be nice if there was also an explanation that small and uppercase letters are required in the list.

I look forward to an update.
Ability to set prices.
I am looking forward to the ability to change the amount depending on the amount assigned.

**Comment by BKPatt** [comment]
Sure. I can add that whenever I get a chance to push the next update
